# Generated by Django 4.1.3 on 2022-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirts',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
