# Generated by Django 4.1.3 on 2022-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0002_shirts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
