# Generated by Django 4.1.3 on 2022-12-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0003_shirts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='image',
            field=models.ImageField(null=True, upload_to='Shirts', verbose_name='Изображение'),
        ),
    ]
