# Generated by Django 4.1.4 on 2022-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0005_shirts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirts',
            name='sizes',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL')], default=2, verbose_name='sizes'),
        ),
    ]
