# Generated by Django 4.1.4 on 2022-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0006_shirts_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='sizes',
            field=models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl')], default='S', max_length=9, verbose_name='sizes'),
        ),
    ]
